//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentsLager.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Journal
    {
        public int Id { get; set; }
        public Nullable<int> IdCompetitions { get; set; }
        public Nullable<int> IdSpecialization { get; set; }
        public Nullable<int> IdGroups { get; set; }
        public Nullable<int> IdMark { get; set; }
    
        public virtual Competitions Competitions { get; set; }
        public virtual Groups Groups { get; set; }
        public virtual Mark Mark { get; set; }
    }
}
