//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentsLager.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class StudLagerDeminEntities : DbContext
    {
        public StudLagerDeminEntities()
            : base("name=StudLagerDeminEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Competitions> Competitions { get; set; }
        public virtual DbSet<Groups> Groups { get; set; }
        public virtual DbSet<Journal> Journal { get; set; }
        public virtual DbSet<Mark> Mark { get; set; }
        public virtual DbSet<Specialization> Specialization { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
